### PR TITLE
Allow for configurable attribute transformer for Nazrin searchable struct

### PR DESCRIPTION
**Pull request by AMHOL**
This allows us to avoid making calls to `Aws::CloudSearch::Client#describe_index_fields`, which will currently be called once for each process, usage as follows:

```ruby
class User
  include Nazrin::Searchable

  searchable_configure do |config|
    config.domain_name = 'my-users-domain'
    config.attribute_transformer = ->(attributes) { attributes }
  end

  def initialize(attributes)
    @attributes = attributes
  end
end
```

### CODE REVIEW

**Comment by tsuwatch** [comment]
Would you tell me more specifically how to use it?

**Comment by AMHOL** [comment]
@tsuwatch in a current project we store JSON files in the repository as artefacts, to synchronise fields to the Cloudsearch domain, so I would use this feature to determine the schema by reading from those files, rather than making a call to `Aws::CloudSearch::Client#describe_index_fields` once in each process on the first call, as it currently does, which I suspect may be causing `Aws::CloudSearch::Errors::Throttling` exceptions. My implementation is:

```ruby
module Search
  class Listing
    class AttributeTransformer
      def call(attributes)
        attributes.each_with_object({}) do |(name, value), hash|
          type = field_types[name]

          if type.end_with?('array')
            hash[name] = value
          else
            hash[name] = value.first
          end
        end
      end

      def field_types
        @field_types ||= artefacts.each_with_object({}) do |file, schema|
          json = JSON.parse(File.read(file))
          name = json['IndexField']['IndexFieldName']
          type = json['IndexField']['IndexFieldType']

          schema[name] = type
        end
      end

      private

      def artefacts
        @artefacts ||= CloudSearch::Artefacts.new.files(:listing_fields)
      end
    end
  end
end
```

**Comment by tsuwatch** [comment]
Thank you, I understand

**Comment by tsuwatch** [comment]
Merged, I would like to avoid raising Throttling error even if the default transformer.
Please let me know if you have any ideas.

**Comment by AMHOL** [comment]
@tsuwatch not without some persistent storage mechanism that we can assume is there?

**Comment by tsuwatch** [comment]
Hmmm, I think so. Thank you for your opinion!

**Pull request merged**
