### PR TITLE
Add specs to DataAccessor

### PR DESCRIPTION
**Pull request by yefim**
How's this? Which other methods need testing?

### CODE REVIEW

**Comment by tsuwatch** [comment]
Thank you 👍 
I think also I need `Nazrin::DataAccessor::Mongoid` specs.
I would like to test whether to load data from mongodb correctly.

**Comment by yefim** [comment]
@tsuwatch I wrote some tests as you suggested :) Let me know what you think!

**Comment by tsuwatch** [comment]
Great work, glad to write the spec. 🎉 
However, testing failed in Travis.
Start mongodb in Travis. https://docs.travis-ci.com/user/database-setup/#MongoDB

**Comment by yefim** [comment]
@tsuwatch done! Tests are passing :)

**Comment by tsuwatch** [comment]
Could you squash your commits?

**Comment by yefim** [comment]
@tsuwatch squashed :)

**Comment by tsuwatch** [comment]
Thanks! {

**Comment by yefim** [comment]
@tsuwatch can you cut a new release? 🙏

**Comment by yefim** [comment]
Thanks!

**Comment by tsuwatch** [comment]
Released in v2.2.0!

**Comment by yefim** [comment]
woooo! Thank you!

**Pull request merged**
