### PR TITLE
Decorate results to allow access to facets

### PR DESCRIPTION
**Pull request by AMHOL**

### CODE REVIEW

**Comment by AMHOL** [comment]
Updated with master & updated spec for struct data accessor

**Comment by tsuwatch** [comment]
Merged, nice work!
Thank you 👍

**Comment by tsuwatch** [comment]
If you don't have additional PRs, I would like to release.

**Comment by AMHOL** [comment]
@tsuwatch nothing else I can think of, for now, a release would be great, thanks for merging.

**Pull request merged**
